CREATE TABLE employee (EMPNO NUMBER),
						ENAME VARCHAR(100),
						JOB CHAR,
						MGR NUMBER,
						HIREDATE DATE,
						SAL NUMBER,
						COMM NUMBER,
						DEPTNO NUMBER)
												

CREATE TABLE DEPARTMENT (DEPTNO NUMBER,
						DNAME VARCHAR(100),
						LOC VARCHAR(100))
						
CREATE TABLE SALGRADE (GRADE INTEGER,
							LOSAL NUMBER,
							HIGHSAL NUMBER)
							
CREATE TABLE MEMBER (MEMBER_ID NUMBER,
								MEMBER_NAME VARCHAR(100),
								MEMBER_ADDREDD VARCHAR(100),
								ACC_OPEN_DATE DATE,
								MEMBERSHIP_TYPE VARCHAR(100),
								FEES_PAID NUMBER,
								MAX_BOOKS_ALLOWED NUMBER,
								PENALTY_AMOUNT NUMBER)
								
CREATE TABLE BOOKS (BOOK_NO NUMBER(6),
									BOOK_NAME VARCHAR2(30),
									AUTHOR_NAME VARCHAR2(30),
									COST NUMBER(7,2))
									
CREATE TABLE ISSUE (LIB_ISSUE_ID NUMBER,
										BOOK_NO NUMBER,
										MEMBER_ID NUMBER,
										ISSUE_DATE DATE,
										RETURN_DATE DATE)
										
CREATE TABLE SUPPLIER (SUPPLIERID NUMBER,
											SUPNAME VARCHAR,
											SUPRANK NUMBER,
											SUPCITY VARCHAR)
											
CREATE TABLE CUSTOMER (CUSTID NUMBER,
							CUSTNAME VARCHAR,
							CUSTINCOME NUMBER,
							CUSTTYPE VARCHAR)
							
CREATE TABLE SHIPMENT (SHIPID NUMBER,
							CUSTID NUMBER,
							SHIPDESTINATION VARCHAR,
							SHIPDATE DATE,
							VEHICLENO NUMBER)
							
CREATE TABLE VEHICLE (VEHNO NUMBER,
							VEHDRIVER VARCHAR,
							DRIVERCITY VARCHAR)
									